services:
  todo_app_backend:
    build:
      context: ./backend
      # dockerfile:
    container_name: todo_app_backend
    restart: always
    environment:
      SERVER_PORT: "8080"
      DB_URI: "postgresql://postgres:postgres@todo_db:5432/postgres?sslmode=disable"
      MAX_IDLE_CONNS: 20
      MAX_OPEN_CONNS: 10
      ENVIRONMENT: PRODUCTION
    ports:
      - "8080:8080"
    depends_on:
      - migrate

  todo_app_frontend:
    build:
      context: ./frontend
      # dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - todo_app_backend
    environment:
      VITE_BACKEND_URL: "http://todo_app_backend:8534/api/v1"

  todo_db:
    container_name: todo_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    build: ./backend
    command: [ "/bin/sh", "-c", "/app/migrate up" ]
    environment:
      DB_URI: "postgresql://postgres:postgres@todo_db:5432/postgres?sslmode=disable"
      MAX_IDLE_CONNS: 20
      MAX_OPEN_CONNS: 10
      ENVIRONMENT: PRODUCTION
    depends_on:
      - todo_db

volumes:
  postgres_data:
